site_url: 'https://bt.srht.site'
site_name: 'bt'
author_name: 'Bradley Taunt'

directories:
  posts: 'posts'
  pages: 'pages'
  public: 'public'
  output: 'build'
  posts_output: 'build/posts'
  pages_output: 'build/'
  
files:
  header: 'header.html'
  footer: 'footer.html'
  root_index: 'index.md'
  posts_index: 'pages/posts.md'
  rss: 'build/index.rss'

misc:
  post_count: 5
